---

- hosts: machine
  sudo: true
  vars:
    - django_app_git_url: ''
    - django_application_name: 'project_name'
    - django_app_git_private_key: "{{ lookup('file', '~/.ssh/github') }}"
    - django_app_site_url: 'mysite.com'
  roles:
    - django-app