---

- hosts: machine
  sudo: true
  vars:
    - django_app_git_url: 'git@bitbucket.org:azhurbilo/motorama.git'
    - django_application_name: 'motorama'
    - django_app_git_private_key: "{{ lookup('file', '~/.ssh/bitbucket') }}"
    - django_app_site_url: 'motorama.com'
  roles:
    - django-app