---

- name: python | install python packages
  apt: name={{item}} state=present
  with_items:
    - python
    - python-dev
    - python3-dev
    - python-software-properties
    - python-pip
    - libmysqlclient-dev
    - libxml2
    - libxml2-dev
    - libxslt1-dev
    - libmemcached-dev
    - libffi-dev
    - libjpeg8-dev
    - mysql-client

- name: python | update pip
  pip: name={{item.name}} version={{item.version}} state=present
  with_items:
    - { name: 'pip', version: 1.5.6 }
