---

- name: python | install python packages
  apt: name={{item}} state=present
  with_items:
    - python
    - python-dev
    - python3-dev
    - python-software-properties
    - python-pip
    - libxml2
    - libxml2-dev
    - libxslt1-dev
    - libmemcached-dev
    - libffi-dev
    - libjpeg8-dev
    - mysql-client

- name: python | update pip
  pip: name={{item.name}} version={{item.version}} state=present
  with_items:
    - { name: 'pip', version: 1.5.6 }

- name: python | install mysql packages
  apt: name={{item}} state=present
  with_items:
    - libmysqlclient-dev
    - mysql-client
    - python-mysqldb
  when: django_db_engine == 'mysql'

- name: python | install postgresql packages
  apt: name={{item}} state=present
  with_items:
    - python-psycopg2
    - postgresql-client
    - libpq-dev
  when: django_db_engine == 'postgresql_psycopg2'
