---

- name: user | Creates directory
  file: path={{django_app_user_home}} state=directory

- name: user | Create the application user
  user: name={{ django_app_user }}
        state=present
        home={{django_app_user_home}}
        createhome=yes
        uid=1010

- name: user | Set owner of that directory to your application
  file: path={{django_app_user_home}} state=directory owner={{ django_app_user }} group={{ django_app_user }}
