---

- name: virtualenv | install virtualenv
  pip: name={{item}}
  with_items:
    - virtualenv
    - virtualenvwrapper

- name: virtualenv | add .bashrc to run virtualenvwrapper
  sudo_user: '{{ app_user }}'
  template: src=user/{{item}} dest=~/{{item}}
  with_items:
    - .profile
    - .bashrc

- name: virtualenv | create the virtualenv
  sudo_user: '{{ app_user }}'
  command: virtualenv {{ virtualenv_path }} --no-site-packages
           creates={{ virtualenv_path }}/bin/activate

- name: virtualenv | add virtualenv wrapper postactivate script
  sudo_user: '{{ app_user }}'
  template: src=virtualenv/postactivate.j2
            dest={{ virtualenv_path }}/bin/postactivate
            mode=640

- name: virtualenv | ensure that permissions are set properly
  file: path={{ virtualenv_path }}
        recurse=yes
        owner={{ app_user }}
        group={{ app_user }}
        state=directory


